### ISSUE TITLE
"Cellular Automata" link does not point to a valid URL

### ISSUE THREAD

**Issue by Epholys** [prathyvsh/formal-systems-in-biology#1]
As the title says, the "Cellular Automata" header link in the README redirects to https://github.com/prathyvsh/formal-systems-in-biology/blob/master/Theory%20of%20self-reproducing%20automata , which is a 404 page.

Thank you for all these resources!

**Comment by prathyvsh** [comment]
Hey there, thank you for the note. This has been fixed!
