### ISSUE TITLE
Chemlambda link

### ISSUE THREAD

**Issue by mbuliga** [prathyvsh/formal-systems-in-biology#10]
Thank you for the mention of chemlambda among the very interesting links. I suggest to use as a link either 
https://chemlambda.github.io/index.html
or if you are interested only in the animations, there is this collection
https://chemlambda.github.io/collection.html

**Comment by prathyvsh** [comment]
Hey, great work there on Chemlambda.

Added both!

**Comment by mbuliga** [comment]
Thank you! Without the contributions from the others repositories it would have been only a mathematical curiosity.

**Comment by prathyvsh** [comment]
> Thank you! Without the contributions from the others repositories it would have been only a mathematical curiosity.

It was amazing to find you landing on this from work in Sub-Riemannian surfaces.

**Comment by mbuliga** [comment]
Thank you for your comment. Please feel free to delete this reply, as it may be not of general interest. 

With the Pure See (working paper) 

https://mbuliga.github.io/quinegraphs/puresee.html

 the story actually returns to the original source, namely the abstract nonsense formalism for space used for sub-riemannian spaces. 

I am no longer on Twitter and I don't know how to contact you, but if you (or anybody) wish to discuss more then please look for one of my addresses from my homepages or if not from my arXiv articles and contact me. In a more general sense I am very attracted by the idea of a new 

https://en.wikipedia.org/wiki/Invisible_College



----- Original Message -----
